### ISSUE TITLE
Importing Custom XYZ dataset

### ISSUE THREAD

**Issue by MiracAydin1** [BaratiLab/AugLiChem#55]
Dear All,

I would like to import custom XYZ dataset to Auglichem. Importing CIF dataset is working fine but when I try to import XYZ dataset for molecule, I realized that MoleculeDatasetWrapper function only supports SMILES format and it gives error for XYZ files. Also, CrystalDatasetWrapper does not support XYZ as expected.

Is there any way to import XYZ files and augment them?

Best regards,

**Comment by MiracAydin1** [comment]
Hello,

If Auglichem support SDF or MOL file format, I can convert my XYZ dataset to them and try molecule augmentation.

**Comment by CoopLo** [comment]
Hello,

Currently MoleculeDatasetWrapper supports SMILES because it is built on RDKit's Mol object. This is hard-coded, but could be overloaded like:

```
def new_getitem(self, index):
        # If augmentation is done, actual dataset is smaller than given indices
        if self.test_mode:
            true_index = index
        else:
            true_index = index // (self.aug_time + 1)

        # Create initial data set
        ### OLD CODE 
        #mol = Chem.MolFromSmiles(self.smiles_data[true_index])

        # YOUR CODE HERE
        mol = Chem.MolFrom[SOME OTHER FORMAT]
        mol = Chem.AddHs(mol)
       
        # Get data x and y
        x = self._get_data_x(mol)
        y = self._get_data_y(true_index)

        # Get edge index and attributes
        edge_index, edge_attr = self._get_edge_index_and_attr(mol)

        # Set up PyG data object
        molecule = PyG_Data(x=x, y=y, edge_index=edge_index, edge_attr=edge_attr,
                            smiles=self.smiles_data[true_index])

        if((not self.test_mode) and (index % (self.aug_time+1) != 0)): # Now retains original
            aug_molecule = self.transform(molecule, seed=self.reproduce_seeds[index])
            return aug_molecule
        elif((not self.test_mode) and self.augment_original):
            aug_molecule = self.transform(molecule, seed=self.reproduce_seeds[index])
            return aug_molecule
        else:
            return molecule
```

Where then you could do `dataset.__getitem__ = new_getitem`. It appears RDKit supports XYZ files and has a `MolFromXYZFile` function.

To utilize the crystal augmentations, I believe you would need some additional processing to get the symmetry information out of your XYZ files. At this time Pymatgen does not appear to be able to easily do this. Please let me know if the overloading above works.

**Comment by CoopLo** [comment]
Closed due to inactivity
